/**
 * shopItems.js — Mystery Fruit & Cosmetic Item Catalog
 * 📅 2026-03-13: Created for XP Shop / Mystery Fruit system
 *
 * Defines all fruit tiers, reward pools, and cosmetic item definitions
 * for Profile Frames, Chat Text Colors, and Trade Card Backgrounds.
 */

// ════════════════════════════════════════════════════════════
//  RARITY TIERS
// ════════════════════════════════════════════════════════════
export const RARITY = {
  COMMON: 'common',
  UNCOMMON: 'uncommon',
  RARE: 'rare',
  LEGENDARY: 'legendary',
  EXCLUSIVE: 'exclusive',
};

export const RARITY_CONFIG = {
  [RARITY.COMMON]:    { label: 'Common',    color: '#94a3b8', emoji: '⚪', bgLight: '#f1f5f9', bgDark: '#1e293b' },
  [RARITY.UNCOMMON]:  { label: 'Uncommon',  color: '#22c55e', emoji: '🟢', bgLight: '#f0fdf4', bgDark: '#14532d' },
  [RARITY.RARE]:      { label: 'Rare',      color: '#3b82f6', emoji: '🔵', bgLight: '#eff6ff', bgDark: '#1e3a5f' },
  [RARITY.LEGENDARY]: { label: 'Legendary', color: '#f59e0b', emoji: '🟡', bgLight: '#fffbeb', bgDark: '#78350f' },
  [RARITY.EXCLUSIVE]: { label: 'Exclusive', color: '#a855f7', emoji: '🟣', bgLight: '#faf5ff', bgDark: '#581c87' },
};

// ════════════════════════════════════════════════════════════
//  COSMETIC TYPES
// ════════════════════════════════════════════════════════════
export const COSMETIC_TYPE = {
  FRAME: 'profileFrame',
  TEXT_COLOR: 'chatTextColor',
  TRADE_BG: 'tradeCardBg',
  BANNER: 'profileBanner',
  CHAT_BG: 'chatBubbleBg',
};

// ════════════════════════════════════════════════════════════
//  PROFILE FRAMES
//  Common frames: CSS border rings (lightweight, simple)
//  Uncommon+: SVG ornamental frames (complex artwork)
//  duration: days (-1 = permanent)
// ════════════════════════════════════════════════════════════
export const FRAMES = {
  // ── COMMON (6) — CSS border rings ──
  magma_ring: {
    id: 'magma_ring',
    name: '🔴 Magma',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.COMMON,
    renderType: 'css',
    duration: 1,
    borderColors: ['#DC2626'],
    borderWidth: 3,
    glowColor: null,
  },
  sea_blue_ring: {
    id: 'sea_blue_ring',
    name: '🌊 Sea Blue',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.COMMON,
    renderType: 'css',
    duration: 1,
    borderColors: ['#0284C7'],
    borderWidth: 3,
    glowColor: null,
  },
  venom_ring: {
    id: 'venom_ring',
    name: '☠️ Venom',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.COMMON,
    renderType: 'css',
    duration: 1,
    borderColors: ['#65A30D'],
    borderWidth: 3,
    glowColor: null,
  },
  dark_energy_ring: {
    id: 'dark_energy_ring',
    name: '🟣 Dark Energy',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.COMMON,
    renderType: 'css',
    duration: 1,
    borderColors: ['#7C3AED'],
    borderWidth: 3,
    glowColor: null,
  },
  lightning_ring: {
    id: 'lightning_ring',
    name: '⚡ Lightning',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.COMMON,
    renderType: 'css',
    duration: 1,
    borderColors: ['#EAB308'],
    borderWidth: 3,
    glowColor: null,
  },
  flame_ring: {
    id: 'flame_ring',
    name: '🔥 Flame',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.COMMON,
    renderType: 'css',
    duration: 1,
    borderColors: ['#EA580C'],
    borderWidth: 3,
    glowColor: null,
  },
  // ── UNCOMMON (5) — SVG frames ──
  devil_fruit_glow: {
    id: 'devil_fruit_glow',
    name: '🍎 Devil Fruit Glow',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.UNCOMMON,
    renderType: 'svg',
    duration: 3,
    borderColors: ['#DC2626', '#F97316'],
    borderWidth: 3,
    glowColor: '#DC262625',
  },
  ice_admiral: {
    id: 'ice_admiral',
    name: '❄️ Ice Admiral',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.UNCOMMON,
    renderType: 'svg',
    duration: 3,
    borderColors: ['#38BDF8', '#BAE6FD'],
    borderWidth: 3,
    glowColor: '#38BDF825',
  },
  tidal_surge: {
    id: 'tidal_surge',
    name: '🌊 Tidal Surge',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.UNCOMMON,
    renderType: 'svg',
    duration: 3,
    borderColors: ['#0369A1', '#0EA5E9'],
    borderWidth: 3,
    glowColor: '#0369A125',
  },
  shadow_blade: {
    id: 'shadow_blade',
    name: '⚔️ Shadow Blade',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.UNCOMMON,
    renderType: 'svg',
    duration: 3,
    borderColors: ['#1E1B4B', '#6366F1', '#312E81'],
    borderWidth: 3,
    glowColor: '#6366F130',
  },
  haki_aura: {
    id: 'haki_aura',
    name: '💪 Haki Aura',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.UNCOMMON,
    renderType: 'svg',
    duration: 3,
    borderColors: ['#1C1917', '#57534E', '#78716C'],
    borderWidth: 3,
    glowColor: '#57534E25',
  },
  // ── RARE (4) — SVG frames ──
  dragon_scale: {
    id: 'dragon_scale',
    name: '🐉 Dragon Scale',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.RARE,
    renderType: 'svg',
    duration: 7,
    borderColors: ['#059669', '#10B981', '#34D399'],
    borderWidth: 5,
    glowColor: '#10B98160',
  },
  phoenix_flame: {
    id: 'phoenix_flame',
    name: '🔥 Phoenix Flame',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.RARE,
    renderType: 'svg',
    duration: 7,
    borderColors: ['#F59E0B', '#EF4444', '#F97316'],
    borderWidth: 5,
    glowColor: '#F59E0B60',
  },
  spirit_sword: {
    id: 'spirit_sword',
    name: '⚔️ Spirit Sword',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.RARE,
    renderType: 'svg',
    duration: 7,
    borderColors: ['#818CF8', '#C7D2FE'],
    borderWidth: 5,
    glowColor: '#818CF860',
  },
  rumble_storm: {
    id: 'rumble_storm',
    name: '⛈️ Rumble Storm',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.RARE,
    renderType: 'svg',
    duration: 7,
    borderColors: ['#FBBF24', '#FFFFFF', '#FDE68A', '#F59E0B'],
    borderWidth: 5,
    glowColor: '#FBBF2460',
  },
  // ── LEGENDARY (4) — SVG frames ──
  awakened_aura: {
    id: 'awakened_aura',
    name: '💫 Awakened Aura',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.LEGENDARY,
    renderType: 'svg',
    duration: 30,
    borderColors: ['#7C3AED', '#EF4444', '#F59E0B', '#3B82F6', '#10B981', '#EC4899'],
    borderWidth: 7,
    glowColor: '#7C3AED80',
  },
  pirate_king: {
    id: 'pirate_king',
    name: '🏴‍☠️ Pirate King',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.LEGENDARY,
    renderType: 'svg',
    duration: 30,
    borderColors: ['#B91C1C', '#FBBF24', '#7F1D1D', '#FDE68A'],
    borderWidth: 7,
    glowColor: '#FBBF2480',
  },
  sea_emperor: {
    id: 'sea_emperor',
    name: '👑 Sea Emperor',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.LEGENDARY,
    renderType: 'svg',
    duration: 30,
    borderColors: ['#1D4ED8', '#FBBF24', '#1E40AF'],
    borderWidth: 7.5,
    glowColor: '#1D4ED880',
  },
  fruit_master: {
    id: 'fruit_master',
    name: '🍇 Fruit Master',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.LEGENDARY,
    renderType: 'svg',
    duration: 30,
    borderColors: ['#7C3AED', '#DC2626', '#059669', '#D946EF'],
    borderWidth: 7,
    glowColor: '#7C3AED80',
  },
  // ── EXCLUSIVE (6) — SVG frames ──
  legendary_awakening: {
    id: 'legendary_awakening',
    name: '⚡👑 Legendary Awakening',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.EXCLUSIVE,
    renderType: 'svg',
    duration: -1, // permanent
    borderColors: ['#7C3AED', '#EF4444', '#FBBF24', '#3B82F6', '#10B981', '#EC4899'],
    borderWidth: 9,
    glowColor: '#7C3AED99',
  },
  void_dragon: {
    id: 'void_dragon',
    name: '🐉🔮 Void Dragon',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.EXCLUSIVE,
    renderType: 'svg',
    duration: -1, // permanent
    borderColors: ['#1E1B4B', '#7C3AED', '#4C1D95', '#6D28D9', '#312E81'],
    borderWidth: 9,
    glowColor: '#7C3AED99',
  },
  mythic_aura: {
    id: 'mythic_aura',
    name: '✨ Mythic Aura',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.EXCLUSIVE,
    renderType: 'svg',
    duration: -1, // permanent
    borderColors: ['#DC2626', '#F59E0B', '#3B82F6', '#10B981', '#7C3AED'],
    borderWidth: 9,
    glowColor: '#DC262699',
  },
  bounty_hunter: {
    id: 'bounty_hunter',
    name: '🎯 Bounty Hunter (Lv10)',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.EXCLUSIVE,
    renderType: 'svg',
    duration: -1, // permanent
    borderColors: ['#B91C1C', '#991B1B'],
    borderWidth: 7,
    glowColor: '#B91C1C99',
  },
  trade_pirate: {
    id: 'trade_pirate',
    name: '💰 Trade Pirate (Lv15)',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.EXCLUSIVE,
    renderType: 'svg',
    duration: -1, // permanent
    borderColors: ['#D97706', '#FBBF24'],
    borderWidth: 7,
    glowColor: '#D9770660',
  },
  sea_legend: {
    id: 'sea_legend',
    name: '⭐ Sea Legend (Lv20)',
    type: COSMETIC_TYPE.FRAME,
    rarity: RARITY.EXCLUSIVE,
    renderType: 'svg',
    duration: -1, // permanent
    borderColors: ['#1D4ED8', '#FBBF24', '#DC2626', '#7C3AED'],
    borderWidth: 4,
    glowColor: '#1D4ED860',
  },
};

// ════════════════════════════════════════════════════════════
//  CHAT TEXT COLORS (8 total)
//  Applied to the sender's message text in group + private chat.
//  Apple-style vibrant mid-tones — readable on both #0f172a and #ffffff.
//  duration: days (-1 = permanent)
// ════════════════════════════════════════════════════════════
export const TEXT_COLORS = {
  // ── COMMON (6) ──
  magma_red: {
    id: 'magma_red',
    name: '🔴 Magma Red',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#EF4444',
  },
  ocean_blue: {
    id: 'ocean_blue',
    name: '🌊 Ocean Blue',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#3B82F6',
  },
  venom_green: {
    id: 'venom_green',
    name: '☠️ Venom Green',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#22C55E',
  },
  flame_orange: {
    id: 'flame_orange',
    name: '🔥 Flame Orange',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#F97316',
  },
  lightning_yellow: {
    id: 'lightning_yellow',
    name: '⚡ Lightning Yellow',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#EAB308',
  },
  ice_cyan: {
    id: 'ice_cyan',
    name: '❄️ Ice Cyan',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#06B6D4',
  },
  // ── UNCOMMON (5) ──
  dark_energy: {
    id: 'dark_energy',
    name: '🟣 Dark Energy',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#A855F7',
  },
  haki_black: {
    id: 'haki_black',
    name: '💪 Haki Black',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#57534E',
  },
  shadow_indigo: {
    id: 'shadow_indigo',
    name: '⚔️ Shadow Indigo',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#6366F1',
  },
  phoenix_amber: {
    id: 'phoenix_amber',
    name: '🔥 Phoenix Amber',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#D97706',
  },
  dragon_emerald: {
    id: 'dragon_emerald',
    name: '🐉 Dragon Emerald',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#059669',
  },
  // ── RARE (4) ──
  spirit_violet: {
    id: 'spirit_violet',
    name: '👻 Spirit Violet',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#7C3AED',
  },
  rumble_gold: {
    id: 'rumble_gold',
    name: '⛈️ Rumble Gold',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#FBBF24',
  },
  crimson_fury: {
    id: 'crimson_fury',
    name: '💀 Crimson Fury',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#DC2626',
  },
  deep_sea_teal: {
    id: 'deep_sea_teal',
    name: '🌊 Deep Sea Teal',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#0D9488',
  },
  // ── LEGENDARY (4) ──
  pirate_gold: {
    id: 'pirate_gold',
    name: '🏴‍☠️ Pirate Gold',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#FFD60A',
  },
  devil_fruit_cycle: {
    id: 'devil_fruit_cycle',
    name: '🍎 Devil Fruit',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: 'candy',
    colors: ['#EF4444', '#7C3AED', '#F59E0B', '#3B82F6'],
  },
  awakened_white: {
    id: 'awakened_white',
    name: '💫 Awakened White',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#E2E8F0',
  },
  sea_emperor_blue: {
    id: 'sea_emperor_blue',
    name: '👑 Emperor Blue',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#1D4ED8',
  },
  // ── EXCLUSIVE (6) ──
  rainbow: {
    id: 'rainbow',
    name: '🌈 Rainbow',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: 'rainbow',
    colors: ['#EF4444', '#F97316', '#EAB308', '#22C55E', '#3B82F6', '#7C3AED'],
  },
  void_purple: {
    id: 'void_purple',
    name: '🔮 Void Purple',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#6D28D9',
  },
  mythic_rose: {
    id: 'mythic_rose',
    name: '✨ Mythic Rose',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#E11D48',
  },
  bounty_crimson: {
    id: 'bounty_crimson',
    name: '🎯 Bounty Crimson',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#991B1B',
  },
  legendary_amber: {
    id: 'legendary_amber',
    name: '⚡ Legendary Amber',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#B45309',
  },
  sea_legend_cyan: {
    id: 'sea_legend_cyan',
    name: '⭐ Sea Legend Cyan',
    type: COSMETIC_TYPE.TEXT_COLOR,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#0891B2',
  },
};

// ════════════════════════════════════════════════════════════
//  TRADE CARD BACKGROUNDS (25 total)
//  Applied as background tint on user's trade posts.
//  Light: vibrant tinted white. Dark: deep jewel tones.
//  duration: days (-1 = permanent)
// ════════════════════════════════════════════════════════════
export const TRADE_BG_COLORS = {
  // ── COMMON (6) ──
  flame_tint: {
    id: 'flame_tint',
    name: '🔥 Flame Tint',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#FECACA',
    darkColor: '#450A0A',
  },
  sea_mist: {
    id: 'sea_mist',
    name: '🌊 Sea Mist',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#BFDBFE',
    darkColor: '#1E3A5F',
  },
  venom_tint: {
    id: 'venom_tint',
    name: '☠️ Venom Tint',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#BBF7D0',
    darkColor: '#14532D',
  },
  smoke_tint: {
    id: 'smoke_tint',
    name: '💨 Smoke',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#E2E8F0',
    darkColor: '#1E293B',
  },
  sand_tint: {
    id: 'sand_tint',
    name: '🏜️ Sand',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#FEF3C7',
    darkColor: '#422006',
  },
  ice_tint: {
    id: 'ice_tint',
    name: '❄️ Ice',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#CFFAFE',
    darkColor: '#164E63',
  },
  // ── UNCOMMON (5) ──
  magma_wash: {
    id: 'magma_wash',
    name: '🌋 Magma Wash',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#FED7AA',
    darkColor: '#431407',
  },
  deep_ocean: {
    id: 'deep_ocean',
    name: '🌊 Deep Ocean',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#A5F3FC',
    darkColor: '#0C4A6E',
  },
  shadow_wash: {
    id: 'shadow_wash',
    name: '⚔️ Shadow Wash',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#C7D2FE',
    darkColor: '#1E1B4B',
  },
  dark_fruit: {
    id: 'dark_fruit',
    name: '🟣 Dark Fruit',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#DDD6FE',
    darkColor: '#2E1065',
  },
  haki_steel: {
    id: 'haki_steel',
    name: '💪 Haki Steel',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#D6D3D1',
    darkColor: '#292524',
  },
  // ── RARE (4) ──
  dragon_jade: {
    id: 'dragon_jade',
    name: '🐉 Dragon Jade',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#A7F3D0',
    darkColor: '#064E3B',
  },
  phoenix_ember: {
    id: 'phoenix_ember',
    name: '🔥 Phoenix Ember',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#FDE68A',
    darkColor: '#451A03',
  },
  spirit_blue: {
    id: 'spirit_blue',
    name: '👻 Spirit Blue',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#BFDBFE',
    darkColor: '#1E3A8A',
  },
  rumble_spark: {
    id: 'rumble_spark',
    name: '⛈️ Rumble Spark',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#FEF08A',
    darkColor: '#3F3F07',
  },
  // ── LEGENDARY (4) ──
  pirate_king_bg: {
    id: 'pirate_king_bg',
    name: '🏴‍☠️ Pirate King',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#FEEAA0',
    darkColor: '#3B2506',
  },
  awakened_violet: {
    id: 'awakened_violet',
    name: '💫 Awakened Violet',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#E9D5FF',
    darkColor: '#3B0764',
  },
  emperor_navy: {
    id: 'emperor_navy',
    name: '👑 Emperor Navy',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#DBEAFE',
    darkColor: '#1E3A5F',
  },
  fruit_master_bg: {
    id: 'fruit_master_bg',
    name: '🍇 Fruit Master',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#FCE7F3',
    darkColor: '#500724',
  },
  // ── EXCLUSIVE (6) ──
  void_abyss: {
    id: 'void_abyss',
    name: '🔮 Void Abyss',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#C4B5FD',
    darkColor: '#1E1145',
  },
  mythic_crimson: {
    id: 'mythic_crimson',
    name: '✨ Mythic Crimson',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#FECDD3',
    darkColor: '#4C0519',
  },
  sea_legend_bg: {
    id: 'sea_legend_bg',
    name: '⭐ Sea Legend',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#BAE6FD',
    darkColor: '#0C4A6E',
  },
  bounty_blood: {
    id: 'bounty_blood',
    name: '🎯 Bounty Blood',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#FECACA',
    darkColor: '#7F1D1D',
  },
  legendary_gold: {
    id: 'legendary_gold',
    name: '⚡ Legendary Gold',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#FDE68A',
    darkColor: '#78350F',
  },
  trade_pirate_bg: {
    id: 'trade_pirate_bg',
    name: '💰 Trade Pirate',
    type: COSMETIC_TYPE.TRADE_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#D4D4D8',
    darkColor: '#18181B',
  },
};

// ════════════════════════════════════════════════════════════
//  PROFILE BANNER GRADIENTS (25 total)
//  Applied to the gradient banner at the top of the profile drawer.
//  Each has a 3-color gradient array [start, mid, end].
//  duration: days (-1 = permanent)
// ════════════════════════════════════════════════════════════
export const BANNER_GRADIENTS = {
  // ── COMMON (6) ──
  flame_burst: {
    id: 'flame_burst',
    name: '🔥 Flame Burst',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.COMMON,
    duration: 1,
    gradient: ['#DC2626', '#F97316', '#FBBF24'],
  },
  ocean_tide: {
    id: 'ocean_tide',
    name: '🌊 Ocean Tide',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.COMMON,
    duration: 1,
    gradient: ['#0369A1', '#0EA5E9', '#38BDF8'],
  },
  venom_mist: {
    id: 'venom_mist',
    name: '☠️ Venom Mist',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.COMMON,
    duration: 1,
    gradient: ['#166534', '#22C55E', '#86EFAC'],
  },
  smoke_cloud: {
    id: 'smoke_cloud',
    name: '💨 Smoke Cloud',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.COMMON,
    duration: 1,
    gradient: ['#334155', '#64748B', '#94A3B8'],
  },
  sand_storm: {
    id: 'sand_storm',
    name: '🏜️ Sand Storm',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.COMMON,
    duration: 1,
    gradient: ['#92400E', '#D97706', '#FDE68A'],
  },
  ice_shard: {
    id: 'ice_shard',
    name: '❄️ Ice Shard',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.COMMON,
    duration: 1,
    gradient: ['#155E75', '#06B6D4', '#A5F3FC'],
  },
  // ── UNCOMMON (5) ──
  magma_flow: {
    id: 'magma_flow',
    name: '🌋 Magma Flow',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    gradient: ['#7F1D1D', '#DC2626', '#F97316'],
  },
  lightning_strike: {
    id: 'lightning_strike',
    name: '⚡ Lightning Strike',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    gradient: ['#422006', '#EAB308', '#FEF08A'],
  },
  shadow_realm: {
    id: 'shadow_realm',
    name: '⚔️ Shadow Realm',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    gradient: ['#1E1B4B', '#4338CA', '#818CF8'],
  },
  dark_aura: {
    id: 'dark_aura',
    name: '🟣 Dark Aura',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    gradient: ['#3B0764', '#7C3AED', '#C084FC'],
  },
  haki_force: {
    id: 'haki_force',
    name: '💪 Haki Force',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    gradient: ['#1C1917', '#44403C', '#78716C'],
  },
  // ── RARE (4) ──
  dragon_breath: {
    id: 'dragon_breath',
    name: '🐉 Dragon Breath',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.RARE,
    duration: 7,
    gradient: ['#064E3B', '#059669', '#34D399'],
  },
  phoenix_rise: {
    id: 'phoenix_rise',
    name: '🔥 Phoenix Rise',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.RARE,
    duration: 7,
    gradient: ['#7F1D1D', '#EF4444', '#FBBF24'],
  },
  spirit_wave: {
    id: 'spirit_wave',
    name: '👻 Spirit Wave',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.RARE,
    duration: 7,
    gradient: ['#312E81', '#6366F1', '#A5B4FC'],
  },
  rumble_flash: {
    id: 'rumble_flash',
    name: '⛈️ Rumble Flash',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.RARE,
    duration: 7,
    gradient: ['#1E3A5F', '#FBBF24', '#FFFFFF'],
  },
  // ── LEGENDARY (4) ──
  pirate_king_banner: {
    id: 'pirate_king_banner',
    name: '🏴‍☠️ Pirate King',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    gradient: ['#7F1D1D', '#B91C1C', '#FBBF24'],
  },
  sea_emperor_banner: {
    id: 'sea_emperor_banner',
    name: '👑 Sea Emperor',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    gradient: ['#1E3A8A', '#1D4ED8', '#FBBF24'],
  },
  awakened_surge: {
    id: 'awakened_surge',
    name: '💫 Awakened Surge',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    gradient: ['#4C1D95', '#7C3AED', '#EF4444'],
  },
  fruit_master_banner: {
    id: 'fruit_master_banner',
    name: '🍇 Fruit Master',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    gradient: ['#7C3AED', '#DC2626', '#059669'],
  },
  // ── EXCLUSIVE (6) ──
  legendary_awakening_banner: {
    id: 'legendary_awakening_banner',
    name: '⚡👑 Legendary Awakening',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    gradient: ['#7C3AED', '#EF4444', '#FBBF24'],
  },
  void_dragon_banner: {
    id: 'void_dragon_banner',
    name: '🐉🔮 Void Dragon',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    gradient: ['#1E1B4B', '#4C1D95', '#7C3AED'],
  },
  mythic_aura_banner: {
    id: 'mythic_aura_banner',
    name: '✨ Mythic Aura',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    gradient: ['#DC2626', '#F59E0B', '#3B82F6'],
  },
  bounty_banner: {
    id: 'bounty_banner',
    name: '🎯 Bounty Hunter',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    gradient: ['#450A0A', '#B91C1C', '#991B1B'],
  },
  trade_pirate_banner: {
    id: 'trade_pirate_banner',
    name: '💰 Trade Pirate',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    gradient: ['#78350F', '#D97706', '#FBBF24'],
  },
  sea_legend_banner: {
    id: 'sea_legend_banner',
    name: '⭐ Sea Legend',
    type: COSMETIC_TYPE.BANNER,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    gradient: ['#1E3A8A', '#FBBF24', '#DC2626'],
  },
};

// ════════════════════════════════════════════════════════════
//  CHAT BUBBLE BACKGROUNDS (25 total)
//  Applied as background tint on user's chat message bubbles.
//  Light: vibrant tinted pastels. Dark: deep jewel tones.
//  duration: days (-1 = permanent)
// ════════════════════════════════════════════════════════════
export const CHAT_BG_COLORS = {
  // ── COMMON (6) ──
  flame_bubble: {
    id: 'flame_bubble',
    name: '🔥 Flame',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#FECACA',
    darkColor: '#450A0A',
  },
  sea_bubble: {
    id: 'sea_bubble',
    name: '🌊 Sea Blue',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#BFDBFE',
    darkColor: '#1E3A5F',
  },
  venom_bubble: {
    id: 'venom_bubble',
    name: '☠️ Venom',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#BBF7D0',
    darkColor: '#14532D',
  },
  smoke_bubble: {
    id: 'smoke_bubble',
    name: '💨 Smoke',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#E2E8F0',
    darkColor: '#1E293B',
  },
  sand_bubble: {
    id: 'sand_bubble',
    name: '🏜️ Sand',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#FEF3C7',
    darkColor: '#422006',
  },
  ice_bubble: {
    id: 'ice_bubble',
    name: '❄️ Ice',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.COMMON,
    duration: 1,
    color: '#CFFAFE',
    darkColor: '#164E63',
  },
  // ── UNCOMMON (5) ──
  magma_bubble: {
    id: 'magma_bubble',
    name: '🌋 Magma',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#FED7AA',
    darkColor: '#431407',
  },
  lightning_bubble: {
    id: 'lightning_bubble',
    name: '⚡ Lightning',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#FEF08A',
    darkColor: '#422006',
  },
  shadow_bubble: {
    id: 'shadow_bubble',
    name: '⚔️ Shadow',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#C7D2FE',
    darkColor: '#1E1B4B',
  },
  dark_bubble: {
    id: 'dark_bubble',
    name: '🟣 Dark Fruit',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#DDD6FE',
    darkColor: '#2E1065',
  },
  haki_bubble: {
    id: 'haki_bubble',
    name: '💪 Haki',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.UNCOMMON,
    duration: 3,
    color: '#D6D3D1',
    darkColor: '#292524',
  },
  // ── RARE (4) ──
  dragon_bubble: {
    id: 'dragon_bubble',
    name: '🐉 Dragon',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#A7F3D0',
    darkColor: '#064E3B',
  },
  phoenix_bubble: {
    id: 'phoenix_bubble',
    name: '🔥 Phoenix',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#FDE68A',
    darkColor: '#451A03',
  },
  spirit_bubble: {
    id: 'spirit_bubble',
    name: '👻 Spirit',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#BFDBFE',
    darkColor: '#1E3A8A',
  },
  rumble_bubble: {
    id: 'rumble_bubble',
    name: '⛈️ Rumble',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.RARE,
    duration: 7,
    color: '#FEF9C3',
    darkColor: '#3F3F07',
  },
  // ── LEGENDARY (4) ──
  pirate_king_bubble: {
    id: 'pirate_king_bubble',
    name: '🏴‍☠️ Pirate King',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#FEEAA0',
    darkColor: '#3B2506',
  },
  awakened_bubble: {
    id: 'awakened_bubble',
    name: '💫 Awakened',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#E9D5FF',
    darkColor: '#3B0764',
  },
  emperor_bubble: {
    id: 'emperor_bubble',
    name: '👑 Emperor',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#DBEAFE',
    darkColor: '#1E3A5F',
  },
  fruit_master_bubble: {
    id: 'fruit_master_bubble',
    name: '🍇 Fruit Master',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.LEGENDARY,
    duration: 30,
    color: '#FCE7F3',
    darkColor: '#500724',
  },
  // ── EXCLUSIVE (6) ──
  void_bubble: {
    id: 'void_bubble',
    name: '🔮 Void',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#C4B5FD',
    darkColor: '#1E1145',
  },
  mythic_bubble: {
    id: 'mythic_bubble',
    name: '✨ Mythic',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#FECDD3',
    darkColor: '#4C0519',
  },
  sea_legend_bubble: {
    id: 'sea_legend_bubble',
    name: '⭐ Sea Legend',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#BAE6FD',
    darkColor: '#0C4A6E',
  },
  bounty_bubble: {
    id: 'bounty_bubble',
    name: '🎯 Bounty',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#FECACA',
    darkColor: '#7F1D1D',
  },
  legendary_bubble: {
    id: 'legendary_bubble',
    name: '⚡ Legendary',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#FDE68A',
    darkColor: '#78350F',
  },
  trade_pirate_bubble: {
    id: 'trade_pirate_bubble',
    name: '💰 Trade Pirate',
    type: COSMETIC_TYPE.CHAT_BG,
    rarity: RARITY.EXCLUSIVE,
    duration: -1,
    color: '#D4D4D8',
    darkColor: '#18181B',
  },
};

// ════════════════════════════════════════════════════════════
//  ALL ITEMS (combined lookup)
// ════════════════════════════════════════════════════════════
export const ALL_ITEMS = { ...FRAMES, ...TEXT_COLORS, ...TRADE_BG_COLORS, ...BANNER_GRADIENTS, ...CHAT_BG_COLORS };

// ════════════════════════════════════════════════════════════
//  FRUIT DEFINITIONS (Mystery Fruit Spin)
//  Each fruit tier has a cost and weighted drop table.
//  Drop table maps rarity → weight (probability).
// ════════════════════════════════════════════════════════════
export const FRUITS = {
  common_fruit: {
    id: 'common_fruit',
    name: 'Common Fruit',
    emoji: '🍎',
    cost: 3,
    color: '#4ADE80',
    description: 'A basic fruit with mostly common rewards',
    dropTable: {
      [RARITY.COMMON]: 70,
      [RARITY.UNCOMMON]: 25,
      [RARITY.RARE]: 5,
      [RARITY.LEGENDARY]: 0,
      [RARITY.EXCLUSIVE]: 0,
    },
  },
  rare_fruit: {
    id: 'rare_fruit',
    name: 'Rare Fruit',
    emoji: '🍇',
    cost: 7,
    color: '#A855F7',
    description: 'Better odds for uncommon and rare items',
    dropTable: {
      [RARITY.COMMON]: 50,
      [RARITY.UNCOMMON]: 35,
      [RARITY.RARE]: 15,
      [RARITY.LEGENDARY]: 0,
      [RARITY.EXCLUSIVE]: 0,
    },
  },
  legendary_fruit: {
    id: 'legendary_fruit',
    name: 'Legendary Fruit',
    emoji: '🔥',
    cost: 15,
    color: '#F59E0B',
    description: 'High chance of rare + legendary rewards',
    dropTable: {
      [RARITY.COMMON]: 0,
      [RARITY.UNCOMMON]: 30,
      [RARITY.RARE]: 50,
      [RARITY.LEGENDARY]: 20,
      [RARITY.EXCLUSIVE]: 0,
    },
  },
  mythical_fruit: {
    id: 'mythical_fruit',
    name: 'Mythical Fruit',
    emoji: '🐉',
    cost: 30,
    color: '#EC4899',
    description: 'The rarest fruit — exclusive items possible!',
    dropTable: {
      [RARITY.COMMON]: 0,
      [RARITY.UNCOMMON]: 0,
      [RARITY.RARE]: 40,
      [RARITY.LEGENDARY]: 40,
      [RARITY.EXCLUSIVE]: 20,
    },
  },
};

// Legacy aliases for backward compatibility with existing DB data
export const EGGS = FRUITS;
export const FRUIT_LIST = Object.values(FRUITS);
export const EGG_LIST = FRUIT_LIST;

// Helper: Get all items of a specific rarity
export const getItemsByRarity = (rarity) => {
  return Object.values(ALL_ITEMS).filter(item => item.rarity === rarity);
};
